# Generated by Django 5.1.6 on 2025-02-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('ivafactura', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('propinafactura', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('montofactura', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('fechafactura', models.DateTimeField()),
                ('formapagofactura', models.CharField()),
                ('idpedido', models.ForeignKey(db_column='idpedido', on_delete=django.db.models.deletion.DO_NOTHING, to='pedido.pedido')),
                ('idpersonal', models.ForeignKey(db_column='idpersonal', on_delete=django.db.models.deletion.DO_NOTHING, to='personal.personal')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
    ]
