# Generated by Django 5.1.6 on 2025-02-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('idmesa', models.AutoField(primary_key=True, serialize=False)),
                ('capmesa', models.SmallIntegerField()),
                ('estadomesa', models.CharField()),
                ('ubimesa', models.CharField()),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
    ]
