# Generated by Django 5.1.6 on 2025-02-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('tipoproducto', models.CharField()),
                ('descripproducto', models.CharField()),
                ('imagenprodcuto', models.BinaryField(blank=True, null=True)),
                ('estadoproducto', models.CharField()),
                ('precioproducto', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('nombreproducto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
